name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: xcodebuild -quiet test -workspace Demo.xcworkspace -scheme Demo -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.0' -derivedDataPath './output'
    - name: Run tests
      run: swift test -v
